# Generated by Django 5.1 on 2024-09-06 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('inventory', '0002_alter_inventory_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='name',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventory'),
        ),
    ]
