# Generated by Django 5.1 on 2024-10-09 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_customer_address_customer_contact_customer_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='freight_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_value',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
    ]
