# Generated by Django 5.1 on 2024-09-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_alter_vendor_options_alter_vendororder_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
