# Generated by Django 5.1 on 2024-09-23 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0012_remove_vendororderitem_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendororderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
