# Generated by Django 5.1 on 2024-09-29 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0013_alter_vendororderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendororder',
            name='freight_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vendororder',
            name='obs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
