# Generated by Django 5.1 on 2024-10-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0014_vendororder_freight_price_vendororder_obs'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendororderitem',
            name='priceWithFreight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
