# Generated by Django 5.1 on 2024-10-02 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0016_alter_vendororderitem_pricewithfreight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendororderitem',
            name='priceWithFreight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
